const resources = {
  en: {
    translation: {
      Welcome: 'Welcome',
      WelcomeBack: 'Welcome Back',
      En: 'En',
      Ru: 'Ru',
      SignUp: 'Sign Up',
      SignIn: 'Sign In',
      MainPage: 'Main Page',
      ProjectDescription:
        'Here, you can seamlessly explore both REST and GraphQL APIs in one powerful and intuitive interface. Whether you are sending HTTP requests or crafting complex GraphQL queries, our platform gives you the tools to interact with APIs effortlessly. Dive into the world of endless possibilities, streamline your workflow, and unlock the full potential of your data. Happy exploring',
      OurUndefinedsTeam: 'Our Undefineds Team',
      AboutTeam: 'About team',
      AboutCourse: 'About Course',
      CourseDescription:
        'React course covers essential technologies and tools, ensuring you are well-equipped for real-world development challenges. You will deepen your expertise in React, Redux, Next.js, TypeScript, master Git and GitHub commands, enhance your ability to debug and optimize with Chrome DevTools. This course is the perfect next step for advancing your frontend development career.',
      TeamDescription:
        'Our team consists of skilled and enthusiastic professionals who are dedicated to crafting outstanding user interfaces. The team is committed to continuous learning, ensuring they stay current with the latest frontend technologies and industry trends. They actively explore new frameworks, libraries, and tools to enhance their work, delivering high-quality and modern digital experiences',
      RomanSokolov: 'Roman Sokolov',
      RomanText:
        'Passionate about crafting intuitive user interfaces and diving deep into backend architecture, I aspire to continually grow as a developer, bringing innovative solutions to every project I undertake.',
      NikitaRadevich: 'Nikita Radevich',
      NikitaText:
        'I have always wanted to try web development because I find its challenges appealing. I know I have much to learn, but with the right approach, I believe I can achieve my goal',
      YanaDyachok: 'Yana Dyachok',
      YanaText:
        'I love the latest technologies and constant development I want to succeed in my future profession, because it is much better to develop in the field that you like.',
      Registration: 'Registration',
      Login: 'Login',
      Email: ' Email',
      Nickname: 'Nickname',
      Password: 'Password',
      ConfirmPassword: 'Confirm password',
      Submit: 'Submit',
      NotFound: 'Ooops... Page not found',
      ErrorMessage: 'Ooops... You are getting an error',
      BackToMain: 'Back to main',
      RemoveSpecialCharacters: 'Remove special characters from nickname',
      NicknameRequired: 'Nickname is required',
      InvalidEmail: 'Invalid email format',
      EmailRequired: 'Email is required',
      PasswordRequired: 'Password is required',
      PasswordContainsNumber: 'Password should contain 1 number',
      PasswordContainsUppercase:
        'Password should contain 1 uppercase letter [A-Z]',
      PasswordContainsLowercase:
        'Password should contain 1 lowercase letter [a-z]',
      PasswordContainsSpecialCharacter:
        'Password should contain 1 special character [!,@,#,$,% ..etc]',
      PasswordMinLength: 'Password must be at least 6 characters long',
      PasswordMustMatch: 'Password must match',
      History: 'History',
      GraphiQLClient: 'GraphiQL Client',
      RESTClient: 'REST Client',
      Response: 'Response',
      NoResponse: 'Enter the URL and click Send to get a response',
      status: 'status',
      Send: 'Send',
      accessGranted: 'Access granted!',
      loading: 'Loading...',
      wrongCredentials: 'Invalid email or password combination!',
      emailAlreadyUse: 'Email you are using is already in use!',
      temporaryBlock:
        'Access to this account has been temporarily disabled due to many failed login attempts. Try again later.',
      unexpectedError: 'An unexpected error occurred!',
      Body: 'Body',
      Headers: 'Headers',
      Key: 'Key',
      Value: 'Value',
      'Add-Header': 'Add header',
    },
  },
  ru: {
    translation: {
      Welcome: 'Добро пожаловать',
      WelcomeBack: 'Добро пожаловать обратно',
      En: 'Анг',
      Ru: 'Рус',
      SignUp: 'Авторизоваться',
      SignIn: 'Войти',
      MainPage: 'Главная Страница',
      ProjectDescription:
        'Здесь вы можете легко изучить API REST и GraphQL в одном мощном и интуитивно понятном интерфейсе. Отправляете ли вы HTTP-запросы или создаете сложные запросы GraphQL, наша платформа предоставляет вам инструменты для легкого взаимодействия с API. Погрузитесь в мир бесконечной возможности, оптимизируйте свой рабочий процесс и раскройте весь потенциал ваших данных. Приятного изучения',
      OurUndefinedsTeam: 'Наша команда Неопределенные',
      AboutTeam: 'Про команду',
      AboutCourse: 'Про курс',
      CourseDescription:
        'Курс React охватывает основные технологии и инструменты, гарантируя, что вы хорошо подготовлены к решению реальных задач. Вы будете углублять ваш опыт работы с React, Redux, Next.js, TypeScript, владением Git и команд GitHub, расширите ваши возможности по отладке и оптимизации с помощью инструментов разработчика Chrome. Этот курс является идеальным следующим шагом для развития вашей карьеры фронтенд-разработчика.',
      TeamDescription:
        'Наша команда состоит из опытных и увлеченных профессионалов, которые посвящают себя созданию выдающихся пользовательских интерфейсов. Команда стремится к непрерывному обучению, гарантируя, что они будут в курсе последних  технологий разработки и тенденций отрасли. Они активно исследуют новые фреймворки, библиотеки и инструменты для улучшения их работы, обеспечивая высококачественный и современный цифровой опыт',
      RomanSokolov: 'Роман Соколов',
      RomanText:
        'Увлеченный созданием интуитивно понятных пользовательских интерфейсов и глубоким погружением в серверную архитектуру, я стремлюсь постоянно расти как разработчик, привнося инновационные решения в каждый проект, за который берусь.',
      NikitaRadevich: 'Никита Радевич',
      NikitaText:
        'Я всегда хотел попробовать себя в веб-разработке, потому что меня привлекали ее задачи. Я знаю, что мне нужно многому научиться, но при правильном подходе я верю, что смогу достичь своей цели.',
      YanaDyachok: 'Яна Дячок',
      YanaText:
        'Я люблю новейшие технологии и постоянное развитие. Хочу добиться успеха в своей будущей профессии, потому что гораздо лучше развиваться в той сфере, которая тебе нравится.',
      Registration: 'Регистрация',
      Login: 'Войти',
      Email: 'Электронная почта',
      Nickname: 'Псевдоним',
      Password: 'Пароль',
      ConfirmPassword: 'Подтвердите пароль',
      Submit: 'Отправить',
      NotFound: 'Упс... Страница не найдена',
      ErrorMessage: 'Упс... Вы получаете ошибку',
      BackToMain: 'Вернуться на главную',
      RemoveSpecialCharacters: 'Удалите специальные символы из псевдонима',
      NicknameRequired: 'Псевдоним обязателен',
      InvalidEmail: 'Неверный формат электронной почты',
      EmailRequired: 'Электронная почта обязательна',
      PasswordRequired: 'Пароль обязателен',
      PasswordContainsNumber: 'Пароль должен содержать 1 цифру',
      PasswordContainsUppercase:
        'Пароль должен содержать 1 заглавную букву [A-Z]',
      PasswordContainsLowercase:
        'Пароль должен содержать 1 строчную букву [a-z]',
      PasswordContainsSpecialCharacter:
        'Пароль должен содержать 1 специальный символ [!,@,#,$,% ..и др.]',
      PasswordMinLength: 'Пароль должен содержать не менее 6 символов',
      PasswordMustMatch: 'Пароль должен совпадать',
      History: 'История',
      GraphiQLClient: 'GraphiQL Клиент',
      RESTClient: 'REST Клиент',
      Response: 'Ответ',
      NoResponse: 'Введите URL и нажмите «Отправить», чтобы получить ответ.',
      status: 'состояние',
      Send: 'Отправить',
      accessGranted: 'Доступ получен!',
      loading: 'Загрузка...',
      wrongCredentials: 'Неверная электронная почта или пароль!',
      emailAlreadyUse:
        'Указанный вами адрес электронной почты уже используется!',
      temporaryBlock:
        'Доступ к этой учетной записи временно отключен из-за множества неудачных попыток входа. Попробуйте еще раз позже.',
      unexpectedError: 'Произошла непредвиденная ошибка!',
      Body: 'Тело',
      Headers: 'Заголовки',
      Key: 'Ключ',
      Value: 'Значение',
      'Add-Header': 'Добавить заголовок',
    },
  },
};
export default resources;
